apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-raissamaciel
  namespace: raissamaciel
spec:
  storageClassName: default-storage-class-raissamaciel
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: raissamaciel

