apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job
  namespace: raissamaciel
spec:
  template:
    metadata:
      labels:
        app: ml-job-raissamaciel
    spec:
      containers:
      - name: ml-container-raissamaciel
        image: quay.io/raissamaciel/ml-container:3.0
        volumeMounts:
        - mountPath: /folder
          name: persistent-storage
        - mountPath: /app/datasets
          name: dataset-volume
      restartPolicy: Never
      volumes:
      - name: dataset-volume
        hostPath:
          path: /home/datasets/spotify
          type: Directory
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-raissamaciel
  backoffLimit: 4